name: Kubescape

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
           curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
           echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Verify kubescape installation
        run: kubescape version

      - name: Scan Yaml files
        run: kubescape scan framework nsa *.yaml  